import About from "@/components/About";
import Alpovka from "@/components/Alpovka";
import ContactMe from "@/components/ContactMe";
import Experience from "@/components/Experience";
import Header from "@/components/Header";
import Projects from "@/components/Projects";
import Skills from "@/components/Skills";
import Head from "next/head";

export default function Home() {
  return (
    <div
      id="root"
      className="bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory z-0 overflow-y-scroll overflow-x-hidden scrollbar scrollbar-track-gray-400/20 sm:scrollbar-track-[rgb(40,40,40)] scrollbar-thumb-orange-300/80"
    >
      <Head>
        <title>Space of Alpovka</title>
        <meta name="description" content="Generated by next.js" />
        <link rel="icon" type="image/png" href="/images/favicon.png" />
      </Head>
      <Header />
      <section id="me" className="snap-start">
        <Alpovka />
      </section>
      <section id="about" className="snap-center">
        <About />
      </section>
      <section id="experience" className="snap-center">
        <Experience />
      </section>
      <section id="skills" className="snap-start">
        <Skills />
      </section>
      <section id="projects" className="snap-start">
        <Projects />
      </section>
      <section id="contact-me" className="snap-start">
        <ContactMe />
      </section>

      <footer className="flex w-full -mt-5 justify-center items-center">
        <p className="text-center text-xs text-black tracking-wide font-mono">
          Alperen KARAVELIOGLU &copy; 2023
        </p>
      </footer>
    </div>
  );
}
